server:
  port: ${CHAT_SERVER_PORT:8083}
  server-header: " "

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: chat-service
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USER}
    password: ${SPRING_RABBITMQ_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    com.orang.chatservice: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.messaging: ${LOG_LEVEL_MESSAGING:INFO}
    org.springframework.web.socket: ${LOG_LEVEL_WEBSOCKET:INFO}

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
  endpoint:
    health:
      show-details: ${HEALTH_SHOW_DETAILS:never}
      probes:
        enabled: true
  health:
    defaults:
      enabled: true

